import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Josefin_Sans as JosefinSans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import ClientLayout from "../providers/clientLayout";
import React from "react";

const josefinSans = JosefinSans({
  subsets: ["latin"],
  variable: "--font-josefin_sans",
});

export const metadata: Metadata = {
  title: "Medrepo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "relative h-full font-josefin_sans antialiased",
          josefinSans.variable
        )}
      >
        <main className="relative flex min-h-screen flex-col">
          {/* <AuthSessionProvider> */}
          <ClientLayout>{children}</ClientLayout>
          {/* </AuthSessionProvider> */}
        </main>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
